name: flutter_ui
description: Fluter user interfaces
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  fluttertoast: ^8.1.2
  intl: ^0.18.0
  package_info: ^2.0.2
  dio: ^5.4.0
  flutter_speed_dial: ^6.2.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.2.5
  backdrop: ^0.8.1
  flutter_staggered_grid_view: ^0.4.1
  sqflite: ^2.3.0
  path: ^1.8.3
  cached_network_image: ^3.2.2
  html: ^0.15.0
  webview_flutter: ^3.0.4
  flutter_easyloading: ^3.0.5
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  internet_connection_checker: ^1.0.0+1
  image_picker: ^1.0.7
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
